# Generated by Django 3.2.9 on 2021-11-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
