# Generated by Django 3.2.9 on 2021-11-26 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('study_duration', models.DurationField(blank=True, null=True)),
                ('last_study_at', models.DateTimeField(blank=True, null=True, verbose_name='last study')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardGroups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
