# Generated by Django 3.2.9 on 2021-11-26 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CardGroups', '0002_cardgroup_study_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardgroup',
            options={'ordering': ['-study_count', 'id']},
        ),
        migrations.AlterModelTable(
            name='cardgroup',
            table='cardgroup',
        ),
    ]
