# Generated by Django 3.2.9 on 2021-12-07 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CardGroups', '0003_auto_20211126_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardgroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
