# Generated by Django 3.2.9 on 2021-11-26 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='card',
            table='card',
        ),
    ]
