# Generated by Django 3.2.9 on 2021-11-29 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0002_auto_20211126_0657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='carGroup',
            new_name='card_group',
        ),
    ]
