# Generated by Django 3.2.9 on 2021-12-07 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0003_rename_cargroup_card_card_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-id']},
        ),
    ]
